export type Lang = "es" | "en" | "it"
export type View = "info" | "letter" | "tape" | "label" | "term"

// ——— Contenido (del CV de Ana, con las erratas corregidas) ——————————————————
export const PROJECTS = [
    { title: "404:NOT FOUND_", cover: "/media/404-not-found/01", year: 2025, at: 2025.15, accent: "#6EA7CC", link: "/projects/404-not-found" },
    { title: "ASH ARCHIVE", cover: "/media/ash-archive/01", year: 2025, at: 2025.38, accent: "#A95A45", link: "/projects/ash-archive" },
    { title: "FRAGMENTOS DE MÍ", cover: "/media/fragmentos-de-mi/01", year: 2025, at: 2025.6, accent: "#6A2028", link: "/projects/fragmentos-de-mi" },
    { title: "EX_CORPO", cover: "/media/ex-corpo/01", year: 2025, at: 2025.82, accent: "#243A2D", link: "/projects/ex-corpo" },
    { title: "AMMAN", cover: "/media/amman/01", year: 2026, at: 2026.3, accent: "#6A2028", link: "/projects/amman" },
]

export const T = {
    es: {
        role: "Estudiante de Diseño de Moda · Sales & Showroom Assistant",
        place: "Madrid",
        views: { info: "Información", letter: "Carta", tape: "Trayectoria", label: "Etiqueta", term: "Terminal" },
        general: "General",
        kind: "Tipo",
        kindV: "Diseñadora de moda en formación",
        where: "Ubicación",
        now: "Ahora",
        nowV: "Grado en Diseño de Moda · ESD Madrid",
        langs: "Idiomas",
        langsV: "Español · Inglés B2 · Italiano B1",
        phone: "Teléfono",
        call: "Llamar",
        about: "Sobre mí",
        aboutP: [
            "La moda es mi vocación y mi forma de expresarme. Actualmente estudio Diseño de Moda y, a través de ello, me inspiro para conectar con las personas.",
            "A través de mi experiencia laboral he adquirido la capacidad de una atención al público excelente, implicándome en la importancia de escuchar, asesorar y ofrecer un servicio cercano y personalizado. No se trata de centrarse únicamente en la venta, sino de ayudar a cada persona a encontrar lo que realmente le hace sentir bien.",
            "Me adapto con rapidez, soy muy observadora y tengo una actitud siempre abierta a aprender. Aspiro a crecer profesionalmente dentro del mundo del retail, aportando mi entusiasmo, sensibilidad por el estilo y un trato humano en cada interacción.",
        ],
        experience: "Experiencia",
        jobs: [
            { when: "jul 2025 — ene 2026", from: 2025.5, to: 2026.05, org: "RENATTA & GO (El Corte Inglés)", role: "Dependienta", items: ["Atención al cliente en el córner.", "Gestión de la caja.", "Reposición y organización del producto en tienda (visual merchandising básico).", "Apoyo en la organización del almacén y control básico de inventario."] },
            { when: "sept 2024 — sept 2025", from: 2024.67, to: 2025.67, org: "KONECTA BPO", role: "Teleoperadora", items: ["Atención telefónica y resolución de incidencias de clientes.", "Gestión de consultas, reclamaciones y tramitación de expedientes.", "Uso de sistemas CRM y herramientas internas de soporte.", "Emisión y recepción de llamadas comerciales."] },
        ],
        education: "Estudios",
        studies: [
            { when: "2024 — actual", from: 2024.7, to: 2026.75, org: "Escuela Superior de Diseño, Madrid", role: "Grado universitario en Diseño de Moda" },
            { when: "2023 — 2024", from: 2023.7, to: 2024.5, org: "IES Puerta Bonita", role: "Grado Superior en Diseño Gráfico" },
            { when: "2021 — 2023", from: 2021.7, to: 2023.5, org: "IES Jorge Guillén", role: "Bachillerato" },
            { when: "2017 — 2021", from: 2017.7, to: 2021.5, org: "IES Jorge Guillén", role: "Educación Secundaria Obligatoria" },
        ],
        skills: "Habilidades",
        skillsL: ["Atención al cliente", "Visual merchandising", "Trabajo en equipo y tolerancia al estrés", "Comunicación efectiva", "Resolución de incidencias", "Gestión de inventarios", "Gestión multicanal", "Sistemas CRM y soporte telefónico", "Ofimática", "Estilo personal"],
        extra: "Formación adicional",
        extraL: ["Curso INSIDE LVMH", "Curso de iniciación al diseño gráfico", "Inglés — B2", "Italiano — B1"],
        projects: "Proyectos",
        download: "Descargar CV",
        print: "Imprimir…",
        contact: "Guardar contacto",
        recruiter: "30 s",
        recruiterTitle: "Ana en 30 segundos",
        recruiterLines: ["Estudiante de Diseño de Moda en ESD Madrid, con base en diseño gráfico.", "Experiencia real de cara al cliente: córner en El Corte Inglés y atención telefónica.", "Proyectos de autor sobre memoria, cuerpo y materia."],
        write: "Escribirle",
        tapeHint: "Arrastra la cinta",
        studying: "Estudiando",
        working: "Trabajando",
        making: "Proyectos",
        idle: "—",
        play: "Reproducir",
        pause: "Pausa",
        todayL: "Hoy",
        tapeStudies: "Estudios",
        tapeWork: "Trabajo",
        today: "HOY",
        labelComp: "Composición",
        labelCompV: ["Diseño de moda", "Diseño gráfico", "Atención al cliente", "Visual merchandising"],
        labelCare: "Instrucciones de cuidado",
        labelCareV: ["Trabaja bien en equipo", "Resiste la presión", "Escucha antes de vender", "Ordena el producto y el almacén", "Se adapta con rapidez"],
        labelSize: "Talla",
        labelMade: "Hecho en Madrid",
        tagFront: "Pieza única",
        tagBack: "No se trata de vender, sino de ayudar a cada persona a encontrar lo que de verdad le hace sentir bien.",
        tagHint: "Clic para girar",
        file: "CV_Ana_Gil.pdf",
        fileHint: "Arrastra el archivo al Dock o haz clic",
        printer: "Impresora",
        copies: "Copias",
        pages: "Páginas",
        pagesV: "Todas",
        paper: "Papel",
        cancel: "Cancelar",
        printing: "Imprimiendo…",
        done: "Listo. CV_Ana_Gil.pdf está en Descargas.",
        pdfNote: "",
        termHelp: "comandos: sobre · experiencia · estudios · habilidades · idiomas · proyectos · contacto · descargar · clear · exit",
        termHire: "Permiso concedido. Abriendo Nuevo mensaje…",
        termUnknown: "comando no encontrado:",
        letterPlace: "Madrid",
        letterTo: "A quien corresponda:",
        letterP: [
            "Me llamo Ana Gil y estudio Diseño de Moda en la ESD Madrid. La moda es mi vocación y mi forma de expresarme: cada proyecto empieza en una herida —un incendio, una ausencia, una memoria que se borra— y termina convertido en objeto: un libro, una colección, una prenda.",
            "En RENATTA & GO (El Corte Inglés) y en Konecta aprendí a escuchar antes de vender, a ordenar el producto y el almacén, y a cuidar a cada persona que llega. Trabajo bien en equipo, resisto la presión y me adapto con rapidez.",
            "Busco un lugar donde seguir creciendo —prácticas, taller, showroom o estudio— al que aportar sensibilidad por el estilo, rigor y muchas ganas de aprender.",
            "Gracias por su tiempo. Estaré encantada de enseñarle mi trabajo en persona.",
        ],
        letterBye: "Un saludo,",
        letterSkip: "Clic para terminar de escribir",
        letterWrite: "Escribir a Ana",
        letterCopy: "Copiar carta",
        letterCopied: "Copiada",
        letterAgain: "Volver a escribir",
    },
    en: {
        role: "Fashion Design Student · Sales & Showroom Assistant",
        place: "Madrid",
        views: { info: "Info", letter: "Cover letter", tape: "Timeline", label: "Label", term: "Terminal" },
        general: "General",
        kind: "Kind",
        kindV: "Fashion designer in training",
        where: "Location",
        now: "Now",
        nowV: "BA Fashion Design · ESD Madrid",
        langs: "Languages",
        langsV: "Spanish · English B2 · Italian B1",
        phone: "Phone",
        call: "Call",
        about: "About me",
        aboutP: [
            "Fashion is my calling and my way of expressing myself. I'm currently studying Fashion Design, and it inspires me to connect with people.",
            "My work experience has taught me excellent customer care: listening, advising and offering a close, personal service. It isn't only about selling, but about helping each person find what truly makes them feel good.",
            "I adapt quickly, I'm very observant and always open to learning. I want to grow professionally in retail, bringing enthusiasm, a sensitivity for style and a human touch to every interaction.",
        ],
        experience: "Experience",
        jobs: [
            { when: "Jul 2025 — Jan 2026", from: 2025.5, to: 2026.05, org: "RENATTA & GO (El Corte Inglés)", role: "Sales assistant", items: ["Customer service at the corner.", "Till management.", "Restocking and in-store product organisation (basic visual merchandising).", "Stockroom organisation and basic inventory control."] },
            { when: "Sep 2024 — Sep 2025", from: 2024.67, to: 2025.67, org: "KONECTA BPO", role: "Call centre agent", items: ["Phone support and customer issue resolution.", "Handling enquiries, complaints and case files.", "CRM systems and internal support tools.", "Inbound and outbound sales calls."] },
        ],
        education: "Education",
        studies: [
            { when: "2024 — present", from: 2024.7, to: 2026.75, org: "Escuela Superior de Diseño, Madrid", role: "BA (Hons) Fashion Design" },
            { when: "2023 — 2024", from: 2023.7, to: 2024.5, org: "IES Puerta Bonita", role: "Higher National Diploma in Graphic Design" },
            { when: "2021 — 2023", from: 2021.7, to: 2023.5, org: "IES Jorge Guillén", role: "Baccalaureate" },
            { when: "2017 — 2021", from: 2017.7, to: 2021.5, org: "IES Jorge Guillén", role: "Secondary education" },
        ],
        skills: "Skills",
        skillsL: ["Customer service", "Visual merchandising", "Teamwork and working under pressure", "Clear communication", "Issue resolution", "Inventory management", "Omnichannel management", "CRM systems and phone support", "Office software", "Personal style"],
        extra: "Further training",
        extraL: ["INSIDE LVMH course", "Introduction to graphic design course", "English — B2", "Italian — B1"],
        projects: "Projects",
        download: "Download CV",
        print: "Print…",
        contact: "Save contact",
        recruiter: "30 s",
        recruiterTitle: "Ana in 30 seconds",
        recruiterLines: ["Fashion Design student at ESD Madrid, with a background in graphic design.", "Real customer-facing experience: an El Corte Inglés corner and phone support.", "Authorial projects on memory, body and matter."],
        write: "Write to her",
        tapeHint: "Drag the tape",
        studying: "Studying",
        working: "Working",
        making: "Projects",
        idle: "—",
        play: "Play",
        pause: "Pause",
        todayL: "Today",
        tapeStudies: "Education",
        tapeWork: "Work",
        today: "TODAY",
        labelComp: "Composition",
        labelCompV: ["Fashion design", "Graphic design", "Customer care", "Visual merchandising"],
        labelCare: "Care instructions",
        labelCareV: ["Works well in a team", "Handles pressure", "Listens before selling", "Keeps product and stockroom in order", "Adapts quickly"],
        labelSize: "Size",
        labelMade: "Made in Madrid",
        tagFront: "One of a kind",
        tagBack: "It isn't about selling, but about helping each person find what truly makes them feel good.",
        tagHint: "Click to flip",
        file: "CV_Ana_Gil.pdf",
        fileHint: "Drag the file to the Dock or click",
        printer: "Printer",
        copies: "Copies",
        pages: "Pages",
        pagesV: "All",
        paper: "Paper",
        cancel: "Cancel",
        printing: "Printing…",
        done: "Done. CV_Ana_Gil.pdf is in Downloads.",
        pdfNote: "The PDF is in Spanish.",
        termHelp: "commands: about · experience · education · skills · languages · projects · contact · download · clear · exit",
        termHire: "Permission granted. Opening New message…",
        termUnknown: "command not found:",
        letterPlace: "Madrid",
        letterTo: "To whom it may concern,",
        letterP: [
            "My name is Ana Gil and I study Fashion Design at ESD Madrid. Fashion is my calling and my way of expressing myself: every project begins with a wound —a fire, an absence, a memory that fades— and ends up as an object: a book, a collection, a garment.",
            "At RENATTA & GO (El Corte Inglés) and at Konecta I learned to listen before selling, to keep product and stockroom in order, and to look after every person who walks in. I work well in a team, handle pressure and adapt quickly.",
            "I'm looking for a place to keep growing —an internship, atelier, showroom or studio— where I can bring a sensitivity for style, rigour and a real eagerness to learn.",
            "Thank you for your time. I would be delighted to show you my work in person.",
        ],
        letterBye: "Kind regards,",
        letterSkip: "Click to finish typing",
        letterWrite: "Write to Ana",
        letterCopy: "Copy letter",
        letterCopied: "Copied",
        letterAgain: "Type again",
    },
    it: {
        role: "Studentessa di Fashion Design · Sales & Showroom Assistant",
        place: "Madrid",
        views: { info: "Informazioni", letter: "Lettera", tape: "Percorso", label: "Etichetta", term: "Terminale" },
        general: "Generale",
        kind: "Tipo",
        kindV: "Fashion designer in formazione",
        where: "Luogo",
        now: "Ora",
        nowV: "Laurea in Fashion Design · ESD Madrid",
        langs: "Lingue",
        langsV: "Spagnolo · Inglese B2 · Italiano B1",
        phone: "Telefono",
        call: "Chiama",
        about: "Chi sono",
        aboutP: [
            "La moda è la mia vocazione e il mio modo di esprimermi. Studio Fashion Design e da lì prendo ispirazione per entrare in contatto con le persone.",
            "Con l'esperienza lavorativa ho imparato a offrire un'ottima assistenza al pubblico: ascoltare, consigliare e dare un servizio vicino e personale. Non si tratta solo di vendere, ma di aiutare ogni persona a trovare ciò che la fa sentire davvero bene.",
            "Mi adatto in fretta, sono molto attenta e sempre pronta a imparare. Voglio crescere nel mondo del retail, portando entusiasmo, sensibilità per lo stile e un tocco umano in ogni interazione.",
        ],
        experience: "Esperienza",
        jobs: [
            { when: "lug 2025 — gen 2026", from: 2025.5, to: 2026.05, org: "RENATTA & GO (El Corte Inglés)", role: "Commessa", items: ["Assistenza clienti nel corner.", "Gestione della cassa.", "Riassortimento e organizzazione del prodotto in negozio (visual merchandising di base).", "Supporto in magazzino e controllo base dell'inventario."] },
            { when: "set 2024 — set 2025", from: 2024.67, to: 2025.67, org: "KONECTA BPO", role: "Operatrice telefonica", items: ["Assistenza telefonica e risoluzione dei problemi dei clienti.", "Gestione di richieste, reclami e pratiche.", "Sistemi CRM e strumenti interni di supporto.", "Chiamate commerciali in entrata e in uscita."] },
        ],
        education: "Formazione",
        studies: [
            { when: "2024 — oggi", from: 2024.7, to: 2026.75, org: "Escuela Superior de Diseño, Madrid", role: "Laurea in Fashion Design" },
            { when: "2023 — 2024", from: 2023.7, to: 2024.5, org: "IES Puerta Bonita", role: "Diploma superiore in Graphic Design" },
            { when: "2021 — 2023", from: 2021.7, to: 2023.5, org: "IES Jorge Guillén", role: "Maturità" },
            { when: "2017 — 2021", from: 2017.7, to: 2021.5, org: "IES Jorge Guillén", role: "Scuola secondaria" },
        ],
        skills: "Competenze",
        skillsL: ["Assistenza clienti", "Visual merchandising", "Lavoro di squadra e gestione dello stress", "Comunicazione efficace", "Risoluzione dei problemi", "Gestione dell'inventario", "Gestione multicanale", "Sistemi CRM e supporto telefonico", "Office", "Stile personale"],
        extra: "Altra formazione",
        extraL: ["Corso INSIDE LVMH", "Corso introduttivo di graphic design", "Inglese — B2", "Italiano — B1"],
        projects: "Progetti",
        download: "Scarica il CV",
        print: "Stampa…",
        contact: "Salva contatto",
        recruiter: "30 s",
        recruiterTitle: "Ana in 30 secondi",
        recruiterLines: ["Studentessa di Fashion Design all'ESD di Madrid, con una base in graphic design.", "Esperienza reale a contatto con il cliente: corner a El Corte Inglés e assistenza telefonica.", "Progetti d'autore su memoria, corpo e materia."],
        write: "Scrivile",
        tapeHint: "Trascina il metro",
        studying: "Studiando",
        working: "Lavorando",
        making: "Progetti",
        idle: "—",
        play: "Riproduci",
        pause: "Pausa",
        todayL: "Oggi",
        tapeStudies: "Studi",
        tapeWork: "Lavoro",
        today: "OGGI",
        labelComp: "Composizione",
        labelCompV: ["Fashion design", "Graphic design", "Assistenza clienti", "Visual merchandising"],
        labelCare: "Istruzioni di cura",
        labelCareV: ["Lavora bene in squadra", "Regge la pressione", "Ascolta prima di vendere", "Tiene in ordine prodotto e magazzino", "Si adatta in fretta"],
        labelSize: "Taglia",
        labelMade: "Fatto a Madrid",
        tagFront: "Pezzo unico",
        tagBack: "Non si tratta di vendere, ma di aiutare ogni persona a trovare ciò che la fa sentire davvero bene.",
        tagHint: "Clic per girare",
        file: "CV_Ana_Gil.pdf",
        fileHint: "Trascina il file nel Dock o fai clic",
        printer: "Stampante",
        copies: "Copie",
        pages: "Pagine",
        pagesV: "Tutte",
        paper: "Carta",
        cancel: "Annulla",
        printing: "Stampa in corso…",
        done: "Fatto. CV_Ana_Gil.pdf è in Download.",
        pdfNote: "Il PDF è in spagnolo.",
        termHelp: "comandi: chi · esperienza · studi · competenze · lingue · progetti · contatto · scarica · clear · exit",
        termHire: "Permesso concesso. Apro Nuovo messaggio…",
        termUnknown: "comando non trovato:",
        letterPlace: "Madrid",
        letterTo: "A chi di competenza,",
        letterP: [
            "Mi chiamo Ana Gil e studio Fashion Design alla ESD di Madrid. La moda è la mia vocazione e il mio modo di esprimermi: ogni progetto nasce da una ferita —un incendio, un'assenza, una memoria che svanisce— e diventa un oggetto: un libro, una collezione, un capo.",
            "Da RENATTA & GO (El Corte Inglés) e da Konecta ho imparato ad ascoltare prima di vendere, a tenere in ordine prodotto e magazzino e a prendermi cura di ogni persona. Lavoro bene in squadra, reggo la pressione e mi adatto in fretta.",
            "Cerco un luogo in cui continuare a crescere —tirocinio, atelier, showroom o studio— portando sensibilità per lo stile, rigore e tanta voglia di imparare.",
            "Grazie per il suo tempo. Sarò felice di mostrarle il mio lavoro di persona.",
        ],
        letterBye: "Cordiali saluti,",
        letterSkip: "Clic per finire di scrivere",
        letterWrite: "Scrivi ad Ana",
        letterCopy: "Copia lettera",
        letterCopied: "Copiata",
        letterAgain: "Riscrivi",
    },
}
export type Copy = (typeof T)["es"]
